// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package api

import "encoding/json"
import "fmt"
import "regexp"
import "time"

type DomainEventEnvelope struct {
	// CorrelationID corresponds to the JSON schema field "correlation_id".
	CorrelationID *string `json:"correlation_id,omitempty,omitzero" yaml:"correlation_id,omitempty" mapstructure:"correlation_id,omitempty"`

	// idempotencia (dedup)
	EventID string `json:"event_id" yaml:"event_id" mapstructure:"event_id"`

	// <service>.<entity>.<action>
	EventType string `json:"event_type" yaml:"event_type" mapstructure:"event_type"`

	// Payload corresponds to the JSON schema field "payload".
	Payload DomainEventEnvelopePayload `json:"payload" yaml:"payload" mapstructure:"payload"`

	// SourceService corresponds to the JSON schema field "source_service".
	SourceService string `json:"source_service" yaml:"source_service" mapstructure:"source_service"`

	// Timestamp corresponds to the JSON schema field "timestamp".
	Timestamp time.Time `json:"timestamp" yaml:"timestamp" mapstructure:"timestamp"`

	// Version corresponds to the JSON schema field "version".
	Version string `json:"version" yaml:"version" mapstructure:"version"`
}

type DomainEventEnvelopePayload map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DomainEventEnvelope) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["event_id"]; raw != nil && !ok {
		return fmt.Errorf("field event_id in DomainEventEnvelope: required")
	}
	if _, ok := raw["event_type"]; raw != nil && !ok {
		return fmt.Errorf("field event_type in DomainEventEnvelope: required")
	}
	if _, ok := raw["payload"]; raw != nil && !ok {
		return fmt.Errorf("field payload in DomainEventEnvelope: required")
	}
	if _, ok := raw["source_service"]; raw != nil && !ok {
		return fmt.Errorf("field source_service in DomainEventEnvelope: required")
	}
	if _, ok := raw["timestamp"]; raw != nil && !ok {
		return fmt.Errorf("field timestamp in DomainEventEnvelope: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in DomainEventEnvelope: required")
	}
	type Plain DomainEventEnvelope
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[a-z_]+\.[a-z_]+\.[a-z_]+$`, string(plain.EventType)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "EventType", `^[a-z_]+\.[a-z_]+\.[a-z_]+$`)
	}
	*j = DomainEventEnvelope(plain)
	return nil
}
