// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for SendNotificationRequestChannel.
const (
	SendNotificationRequestChannelEMAIL SendNotificationRequestChannel = "EMAIL"
	SendNotificationRequestChannelINAPP SendNotificationRequestChannel = "IN_APP"
)

// Valid indicates whether the value is a known member of the SendNotificationRequestChannel enum.
func (e SendNotificationRequestChannel) Valid() bool {
	switch e {
	case SendNotificationRequestChannelEMAIL:
		return true
	case SendNotificationRequestChannelINAPP:
		return true
	default:
		return false
	}
}

// Defines values for SentNotificationChannel.
const (
	SentNotificationChannelEMAIL SentNotificationChannel = "EMAIL"
	SentNotificationChannelINAPP SentNotificationChannel = "IN_APP"
)

// Valid indicates whether the value is a known member of the SentNotificationChannel enum.
func (e SentNotificationChannel) Valid() bool {
	switch e {
	case SentNotificationChannelEMAIL:
		return true
	case SentNotificationChannelINAPP:
		return true
	default:
		return false
	}
}

// Defines values for SentNotificationSendStatus.
const (
	FAILED  SentNotificationSendStatus = "FAILED"
	PENDING SentNotificationSendStatus = "PENDING"
	SENT    SentNotificationSendStatus = "SENT"
)

// Valid indicates whether the value is a known member of the SentNotificationSendStatus enum.
func (e SentNotificationSendStatus) Valid() bool {
	switch e {
	case FAILED:
		return true
	case PENDING:
		return true
	case SENT:
		return true
	default:
		return false
	}
}

// SendNotificationRequest defines model for SendNotificationRequest.
type SendNotificationRequest struct {
	Channel        SendNotificationRequestChannel `json:"channel"`
	RecipientEmail openapi_types.Email            `json:"recipient_email"`
	RecipientId    openapi_types.UUID             `json:"recipient_id"`
	SourceEventId  *openapi_types.UUID            `json:"source_event_id,omitempty"`
	SourceService  *string                        `json:"source_service,omitempty"`
	Subject        string                         `json:"subject"`
	TemplateCode   *string                        `json:"template_code,omitempty"`

	// TemplateVars Variables to substitute in the template (e.g. {schedule_name, ficha}).
	TemplateVars *map[string]string `json:"template_vars,omitempty"`
}

// SendNotificationRequestChannel defines model for SendNotificationRequest.Channel.
type SendNotificationRequestChannel string

// SentNotification defines model for SentNotification.
type SentNotification struct {
	Channel     *SentNotificationChannel    `json:"channel,omitempty"`
	Id          *openapi_types.UUID         `json:"id,omitempty"`
	RecipientId *openapi_types.UUID         `json:"recipient_id,omitempty"`
	SendStatus  *SentNotificationSendStatus `json:"send_status,omitempty"`
	SentAt      *time.Time                  `json:"sent_at,omitempty"`
	Subject     *string                     `json:"subject,omitempty"`
}

// SentNotificationChannel defines model for SentNotification.Channel.
type SentNotificationChannel string

// SentNotificationSendStatus defines model for SentNotification.SendStatus.
type SentNotificationSendStatus string

// SendNotificationJSONRequestBody defines body for SendNotification for application/json ContentType.
type SendNotificationJSONRequestBody = SendNotificationRequest
